@startuml

title __Strategy Pattern StringListReverter__\n

  namespace at.fhj.swd {
    enum RevertFlavor {
      SHALLOW_COPY
      DEEP_COPY
      IN_PLACE
      IMMUTABLE
    }
  }
  

  namespace at.fhj.swd {
    interface at.fhj.swd.RevertFactory {
        {static} + INSTANCE : Factory
        {abstract} + createRevertAlgorithm(RevertFlavor) : StringListRevertStrategy
    }
  }
  

  namespace at.fhj.swd {
    class at.fhj.swd.RevertFactoryImpl {
        ~ RevertFactoryImpl() <<create>>
        + createRevertAlgorithm(RevertFlavor) : StringListRevertStrategy
    }
  }
  

  namespace at.fhj.swd {
    interface at.fhj.swd.StringListRevertStrategy {
        {abstract} + revert(List<String>) : List<String>
    }
  }
  

  namespace at.fhj.swd {
    class at.fhj.swd.ShallowCopyRevert {
        ~ ShallowCopyRevert() <<create>>
        + revert(List<String>) : List<String>
    }
  }
  

  namespace at.fhj.swd {
    class at.fhj.swd.DeepCopyRevert {
        ~ DeepCopyRevert()<<create>>
        + revert(List<String>) : List<String>
    }
  }
  

  namespace at.fhj.swd {
    class at.fhj.swd.InplaceRevert {
        ~ InplaceRevert() <<create>>
        + revert(List<String>) : List<String>
    }
  }

  namespace at.fhj.swd {
    class at.fhj.swd.ImmutableRevert {
        ~ ImmutableRevert() <<create>>
        + revert(List<String>) : List<String>
    }
  }



  at.fhj.swd.RevertFactoryImpl ..|> at.fhj.swd.RevertFactory
  at.fhj.swd.RevertFactoryImpl .up.> at.fhj.swd.ShallowCopyRevert
  at.fhj.swd.RevertFactoryImpl .up.> at.fhj.swd.DeepCopyRevert
  at.fhj.swd.RevertFactoryImpl .up.> at.fhj.swd.InplaceRevert
  at.fhj.swd.RevertFactoryImpl .up.> at.fhj.swd.ImmutableRevert

  at.fhj.swd.ShallowCopyRevert .up.|> at.fhj.swd.StringListRevertStrategy
  at.fhj.swd.DeepCopyRevert .up.|> at.fhj.swd.StringListRevertStrategy
  at.fhj.swd.InplaceRevert .up.|> at.fhj.swd.StringListRevertStrategy
  at.fhj.swd.ImmutableRevert .up.|> at.fhj.swd.StringListRevertStrategy


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
