package org.se.lab.legacy;


/**
* org/se/lab/user_service.java
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/UserService.idl
* Monday, April 22, 2013 8:50:11 PM CEST
*/

public interface user_service  
{
	  void add_user(int id, String username, String password);
	  void login_user(String username, String password, org.omg.CORBA.BooleanHolder success);
	  
} // interface user_service
